-- 1. Stammdaten (ohne Fremdschlüssel)
CREATE TABLE Kategorie (
    kategorie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE Lieferant (
    lieferant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firmenname VARCHAR2(100) NOT NULL,
    ansprechpartner VARCHAR2(100),
    telefon VARCHAR2(30)
);

CREATE TABLE Mitarbeiter (
    mitarbeiter_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR2(50) NOT NULL,
    nachname VARCHAR2(50) NOT NULL,
    rolle VARCHAR2(30) DEFAULT 'Verkäufer' NOT NULL
);

CREATE TABLE Kunde (
    kunde_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR2(50) NOT NULL,
    nachname VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(30),
    geburtsdatum DATE NOT NULL
);

-- 2. Artikel (mit Fremdschlüsseln zu Kategorie und Lieferant)
CREATE TABLE Artikel (
    artikel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bezeichnung VARCHAR2(100) NOT NULL,
    ean_code VARCHAR2(13) UNIQUE NOT NULL,
    verkaufspreis NUMBER(10,2) NOT NULL,
    lagerbestand NUMBER DEFAULT 0 NOT NULL,
    altersfreigabe NUMBER DEFAULT 0 NOT NULL,
    kategorie_id NUMBER NOT NULL,
    lieferant_id NUMBER NOT NULL,
    CONSTRAINT chk_bestand CHECK (lagerbestand >= 0),
    CONSTRAINT chk_alter CHECK (altersfreigabe IN (0, 16, 18)),
    CONSTRAINT fk_artikel_kategorie FOREIGN KEY (kategorie_id) REFERENCES Kategorie(kategorie_id),
    CONSTRAINT fk_artikel_lieferant FOREIGN KEY (lieferant_id) REFERENCES Lieferant(lieferant_id)
);

-- 3. Transaktions-Kopfdaten (Verkauf & Bestellung)
CREATE TABLE Verkauf (
    verkauf_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum_zeit DATE DEFAULT SYSDATE NOT NULL,
    gesamtbetrag NUMBER(10,2) DEFAULT 0 NOT NULL,
    mitarbeiter_id NUMBER NOT NULL,
    CONSTRAINT fk_verkauf_mitarbeiter FOREIGN KEY (mitarbeiter_id) REFERENCES Mitarbeiter(mitarbeiter_id)
);

CREATE TABLE Bestellung (
    bestellung_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bestelldatum DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'offen' NOT NULL,
    lieferant_id NUMBER NOT NULL,
    CONSTRAINT chk_status CHECK (status IN ('offen', 'versendet', 'geliefert', 'storniert')),
    CONSTRAINT fk_bestellung_lieferant FOREIGN KEY (lieferant_id) REFERENCES Lieferant(lieferant_id)
);

-- 4. Auflösungstabellen (m:n) mit zusammengesetzten Schlüsseln
CREATE TABLE Verkaufsposition (
    verkauf_id NUMBER NOT NULL,
    artikel_id NUMBER NOT NULL,
    menge NUMBER DEFAULT 1 NOT NULL,
    einzelpreis NUMBER(10,2) NOT NULL,
    PRIMARY KEY (verkauf_id, artikel_id),
    CONSTRAINT chk_verkauf_menge CHECK (menge > 0),
    CONSTRAINT fk_pos_verkauf FOREIGN KEY (verkauf_id) REFERENCES Verkauf(verkauf_id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_artikel FOREIGN KEY (artikel_id) REFERENCES Artikel(artikel_id)
);

CREATE TABLE Bestellposition (
    bestellung_id NUMBER NOT NULL,
    artikel_id NUMBER NOT NULL,
    bestellmenge NUMBER NOT NULL,
    gelieferte_menge NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (bestellung_id, artikel_id),
    CONSTRAINT chk_bestell_menge CHECK (bestellmenge > 0),
    CONSTRAINT fk_bpos_bestellung FOREIGN KEY (bestellung_id) REFERENCES Bestellung(bestellung_id) ON DELETE CASCADE,
    CONSTRAINT fk_bpos_artikel FOREIGN KEY (artikel_id) REFERENCES Artikel(artikel_id)
);

CREATE TABLE Zeitschriften_Abo (
    kunde_id NUMBER NOT NULL,
    artikel_id NUMBER NOT NULL,
    menge NUMBER DEFAULT 1 NOT NULL,
    wochentag VARCHAR2(15) NOT NULL,
    PRIMARY KEY (kunde_id, artikel_id),
    CONSTRAINT chk_abo_menge CHECK (menge > 0),
    CONSTRAINT fk_abo_kunde FOREIGN KEY (kunde_id) REFERENCES Kunde(kunde_id) ON DELETE CASCADE,
    CONSTRAINT fk_abo_artikel FOREIGN KEY (artikel_id) REFERENCES Artikel(artikel_id)
);